id: test
name: test

prefixes:
  test: http://example.org/test

imports:
  - http://w3id.org/linkml/types

default_range: string
default_prefix: test

slots:
  a:
    multivalued: true
    pattern: '^A'
  b:
    multivalued: false
    pattern: '^B'
  c:

classes:
  A:
    slots:
      - a
      - b
      - c
    tree_root: true
