# yaml-language-server: $schema=https://w3id.org/linkml/meta.schema.json
id: https://w3id.org/linkml/linter/config
name: linter-config
title: LinkML Linter Configuration Datamodel
description: >-
  A datamodel describing the configuration file accepted by the linkml-lint command
license: https://creativecommons.org/publicdomain/zero/1.0/

prefixes:
  linkml: https://w3id.org/linkml/
  lintcfg: https://w3id.org/linkml/linter/config

default_prefix: lintcfg
default_range: string

imports:
  - linkml:types

classes:
  Config:
    tree_root: true
    attributes:
      no_empty_title:
        range: RuleConfig
        description: >-
          Disallow empty titles on schema elements. Autofix will transform the element's
          name into a title.
      permissible_values_format:
        range: PermissibleValuesFormatRuleConfig
        description: >-
          Enforce consistent formatting of enum permissible values. Not auto-fixable.
      tree_root_class:
        range: TreeRootClassRuleConfig
        description: >-
          Require a single class with `tree_root: true` and optionally verify that class's 
          name. Autofix will create a new class with `tree_root: true`, a name based on
          the rule configuration, and slots for existing classes.
      recommended:
        range: RecommendedRuleConfig
        description: >-
          Require any slot in the metamodel with `recommended: true` (e.g. description)
          to be provided. Not auto-fixable.
      no_xsd_int_type:
        range: RuleConfig
        description: >-
          Disallow use of `uri: xsd:int` in type definitions. Autofix will change the 
          uri to xsd:integer.

  RuleConfig:
    attributes:
      level:
        range: RuleLevel
        required: true

  PermissibleValuesFormatRuleConfig:
    is_a: RuleConfig
    attributes:
      format:
        range: string
        description: >-
          Default: "uppersnake"
          Special values "snake", "uppersnake", "camel", and "kebab" will be recognized,
          otherwise the value will be interpreted as a regular expression.

  TreeRootClassRuleConfig:
    is_a: RuleConfig
    attributes:
      root_class_name:
        range: string
        description: >-
          Default: Container
          If a class definition with `tree_root: true` is not found and autofix is enabled,
          this string will be used as the name of the class added to the schema.
      validate_existing_class_name:
        range: boolean
        description: >-
          Default: false
          If true, in addition to validating that a `tree_root: true` ClassDefinition exists,
          the rule will also validate that is has the name provided by the `class_name` option.

  RecommendedRuleConfig:
    is_a: RuleConfig
    attributes:
      include:
        range: string
        multivalued: true
        description: >-
          Default: []
          If specified, only elements with the provided names will be checked
      exclude:
        range: string
        multivalued: true
        description: >-
          Default: []
          All elements except the ones with names specified in this list will be checked 
        


enums:
  RuleLevel:
    permissible_values:
      disabled:
        description: The rule will not be checked
      warning:
        description: A violation of a rule at this level is a minor issue that should be fixed
      error:
        description: A violation of a rule at this level is a major issue that must be fixed
