no_empty_title:
  level: disabled
permissible_values_format:
  level: disabled
  format: uppersnake
tree_root_class:
  level: disabled
  root_class_name: Container
  validate_existing_class_name: false
recommended:
  level: disabled
  include: []
  exclude: []
